### ISSUE TITLE
Script stops

### ISSUE THREAD

**Issue by jgkibert** [bpaauwe/AmbientWeatherNS#3]
what is causing this? Happens daily. Help please.

019-12-30 17:16:26,448 [Controller] [INFO ] Short Poll:  Ambient Weather Updating
2019-12-30 17:16:32,012 [Controller] [ERROR] Exception in thread Controller:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 856, in _parseInput
    self.shortPoll()
  File "./ambientweather-poly.py", line 54, in shortPoll
    self.ambient_weather_update()
  File "./ambientweather-poly.py", line 223, in ambient_weather_update
    LOGGER.info(pws['macAddress'])
TypeError: string indices must be integers

**Comment by bpaauwe** [comment]
I think you're using the other Ambient weather node server https://github.com/simplextech/udi-poly-ambientweather, not mine.

**Comment by jgkibert** [comment]
You are correct, I'm so sorry for the inconvenience

**Comment by jgkibert** [comment]
My bad, so sorry.
